version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:9.4
    networks:
      - noosfero-net
    env_file:
      - config/docker/prod/production.env
    volumes:
      - pg-prod-data:/var/lib/postgresql/data

  noosfero:
    container_name: noosfero
    build:
      context: .
      dockerfile: ./config/docker/prod/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - noosfero-net
    env_file:
      - config/docker/prod/production.env 
    volumes:
      - ./tmp/backup:/tmp/backup
      - noosfero-public:/noosfero/public
      - noosfero-log:/noosfero/log

  nginx:
    container_name: nginx
    image: nginx:1.14
    depends_on:      
      - noosfero    
    ports:      
      - 80:80
    networks:
      - noosfero-net  
    env_file:
      - config/docker/prod/production.env
    volumes:
      - noosfero-public:/noosfero/public
      - noosfero-log:/noosfero/log
      - ./config/docker/prod/nginx-start.sh:/tmp/nginx-start.sh
      - ./config/docker/prod/templates/nginx.template:/tmp/nginx.template
    command: /tmp/nginx-start.sh

volumes:
  pg-prod-data: {}
  noosfero-public:
  noosfero-log:

networks:
  noosfero-net:
    name: noosfero-net
