source "https://rubygems.org"

gem 'omniauth', '~> 1.3.1'
gem 'omniauth-facebook', '~> 4.0.0'
gem 'omniauth-twitter', '~> 1.2.1'
gem "omniauth-google-oauth2", '~> 0.4.1'
gem "omniauth-oauth2", '~> 1.4.0'
gem "omniauth-github", '~> 1.1.2'
