source "https://rubygems.org"

gem 'omniauth', '~> 1.2.2'
gem 'omniauth-facebook', '~> 2.0.0'
gem 'omniauth-twitter', '~> 1.0.1'
gem "omniauth-google-oauth2", '~> 0.2.6'
gem "omniauth-oauth2", '~> 1.3.1'
gem "omniauth-github", '~> 1.1.2'
