FROM httpd:2.4.35

RUN apt-get update -qq && \
    apt-get install -y apache2

RUN a2enmod deflate expires proxy proxy_balancer proxy_http rewrite

COPY ./templates/mysite.template /etc/apache2/sites-available/$MYSITE

RUN a2ensite $MYSITE

CMD ["invoke-rc.d", "apache2", "restart"]
CMD ["service", "apache2", "start"]
