FROM million12/varnish

RUN yum update -y

VOLUME ["/var/lib/varnish", "/etc/varnish"]

COPY templates/ports-conf.template /etc/apache2/ports.conf
COPY templates/default-conf.template /etc/apache2/sites-enabled/000-default.conf
COPY templates/varnish.template /etc/default/varnish
COPY templates/default-vcl.template /etc/varnish/default.vcl
COPY templates/varnishncsa.template /etc/default/varnishncsa
COPY templates/init-varnish.template /etc/init.d/varnish
COPY varnish-start.sh /home/varnish-start.sh
