#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_get noosfero-apache/enable_apache_site
enable_apache_site="$RET"

if test -x /usr/sbin/a2enmod; then
  a2enmod deflate expires proxy proxy_balancer proxy_http rewrite
fi

if which update-noosfero-apache >/dev/null; then


  update-noosfero-apache

  if [ "$enable_apache_site" = 'true' ]; then
    a2ensite noosfero.conf
    invoke-rc.d apache2 reload
  fi
fi

#DEBHELPER#
