#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

Environment.default.categories.destroy_all

def new_category(parent, name, color = nil)
  category = Environment.default.categories.build(:name => name, :display_color => color, :parent_id => (parent ? parent.id: nil))
  category.save!
  category
end

def new_region(parent, name, color = nil)
  region = Environment.default.regions.build(:name => name, :display_color => color, :parent_id => (parent ? parent.id: nil))
  region.save!
  region
end

tematicas = new_category(nil, 'Temáticas', 1)
new_category(tematicas, 'Finanças Solidárias')
new_category(tematicas, 'Marco Legal')
new_category(tematicas, 'Software Livre')

territorios = new_region(nil, 'Territórios', 2)
ba = new_region(territorios, 'Bahia')
df = new_region(territorios, 'Distrito Federal')
rs = new_region(territorios, 'Rio Grande do Sul')

cadeias = new_category(nil, 'Cadeias', 3)
new_category(cadeias, 'Algodão')
new_category(cadeias, 'Tecnologia de Informação')


# validators
ba.validators << Organization.create!(:name => "Colivre", :identifier => 'colivre')
ba.validators << Organization.create!(:name => "Forum Baiano de Economia Solidaraia", :identifier => 'ecosolbahia')

df.validators << Organization.create!(:name => 'Caritas', :identifier => 'caritas')
df.validators << Organization.create!(:name => 'Forum Brasileiro de Economia Solidaria', :identifier => 'fbes')

rs.validators << Organization.create!(:name => 'Associacao Software Livre.Org', :identifier => 'asl')
rs.validators << Organization.create!(:name => 'Forum Gaucho de Economia Solidaria', :identifier => 'ecosolrs')

