#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'
include GetText
ActionController::Base.init_gettext 'noosfero'
set_locale_all 'pt_BR'

env = Environment.default

case $ARGV[0]
when 'inactive-enterprise'
  offset = 0
  excluded = [env.inactive_enterprise_template, env.enterprise_template]
  template = excluded.first

  while enterprise = Enterprise.find(:first, :conditions => {:enabled => false}, :offset => offset)
    # do nothing with templates
    next if excluded.include?(enterprise)

    # do the thing
    enterprise.apply_template(template)
    puts "#{offset} - #{enterprise.identifier}"

    # bring it on ...
    offset = offset + 1
  end
when 'active-enterprise'
  active_enterprises = Enterprise.find(:all, :conditions => {:enabled => true}) - [env.enterprise_template, env.enterprise_template]
  active_enterprises.each { |enterprise| enterprise.apply_template(env.enterprise_template) }
when 'community'
  communities = Community.find(:all) - [Community['espaco'], Community['anarquismo']]
  communities.each { |community|
    puts 'c: ' + community.identifier
    community.apply_template(env.community_template)
    community.reload
    puts 'template applied'
    community.articles.each { |article|
      puts 'including ' + article.path + ' in the blog'
      if !article.blog? && !article.is_a?(RssFeed)
        article.parent_id = community.blog.id
        article.save!
      end
    }
  }
end


