#!/bin/sh

set -e

build() {
  cp config/database.yml.sqlite3 config/database.yml && /usr/bin/rake db:schema:load && /usr/bin/rake
}

# build the code in the VCS
build

# build the release tarball as well
version=$(ruby -Ilib -rnoosfero -e 'puts Noosfero::VERSION')
rm -rf pkg/ && rake -f Rakefile.pkg && cd pkg/noosfero-${version}/ && build
