#!/bin/sh

set -e

export RAILS_ENV=development

stop() {
  echo "Stopping ..."
  ./script/delayed_job stop
  ./script/feed-updater stop
  whenever --clear-crontab
  if [ -f tmp/pids/thin.pid ]; then
    kill -9 $(cat tmp/pids/thin.pid)
    rm -f tmp/pids/thin.pid
  fi
  exit
}

start() {
  rake db:abort_if_pending_migrations
  ./script/feed-updater start
  ./script/delayed_job start
  trap stop INT TERM
  whenever --write-crontab --set 'environment=development'
  if [ -z "$RAILS_RELATIVE_URL_ROOT" ]; then
    rails s $@
  else
    mkdir -p log
    touch log/development.log
    thin \
      --prefix "$RAILS_RELATIVE_URL_ROOT" \
      --pid tmp/pids/thin.pid \
      --daemonize \
      start
    tail -n 0 -f log/development.log || true
  fi
}

start $@
