#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

(FeedReaderBlock.find(:all) + ExternalFeed.find(:all, :conditions => {:enabled => true})).each do |container|
  unless container.address.nil?
    begin
      handler = FeedHandler.new
      handler.process(container)
    rescue Exception => ex
      $stderr.puts("Unknown error from %s ID %d\n%s" % [container.class.name, container.id, ex.to_s])
      $stderr.puts("Backtrace:\n%s" % ex.backtrace.join("\n"))
    end
  end
end
