#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

system "rm #{Rails.root}/tmp/*.db"
system "rm #{Rails.root}/db/*.db"
system "rm -rf #{Rails.root}/public/articles"
system "rake db:migrate VERSION=0"
system "rake db:migrate"
system "#{Rails.root}/script/anhetegua"
system "rake db:test:prepare"
