#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

# turn on autoflush
STDOUT.sync = true

QUALIFIERS = ['Organic', 'Ecological', 'Biodynamic farming', 'Sustainable', 'Agroecological', 'Craft', 'Free as in freedom']
CERTIFIERS = ['FBES', 'Colivre', 'Circuito Fora do Eixo', 'Instituto Paulo Freire', 'Free Software Foundation', 'Linux Foundation', 'GNU', 'Perl Foundation']

environment = Environment.default

printf "Creating qualifiers and certifiers: "
CERTIFIERS.each do |certifier_name|
  Certifier.create!(:name => certifier_name, :environment => environment)
  print '.'
end

QUALIFIERS.each do |qualifier_name|
  Qualifier.create!(:name => qualifier_name, :environment => environment)
  print '.'
end

Qualifier.all.each do |qualifier|
  Certifier.all.sort_by{rand}.slice(0, CERTIFIERS.size / 2).each do |certifier|
    QualifierCertifier.create!(:qualifier => qualifier, :certifier => certifier)
    print '.'
  end
end
puts " done!"
