#!/usr/bin/env ruby

require_relative "../config/environment"
require_relative "../lib/sample_data"
include SampleData

def new_category(parent, name, color = nil)
  save $environment.categories.build(name: name, display_color: color, parent_id: (parent ? parent.id : nil), display_in_menu: true)
end

def new_region(parent, name, color = nil)
  save $environment.regions.build(name: name, display_color: color, parent_id: (parent ? parent.id : nil), display_in_menu: true)
end

def new_state(parent, name)
  save State.new(name: name, parent_id: parent ? parent.id : nil, environment: $environment)
end

print "Creating categories: "
tematicas = new_category(nil, "Tem\u00E1ticas", 1)
new_category(tematicas, "Forma\u00E7\u00E3o")
new_category(tematicas, "Produ\u00E7\u00E3o, comercializa\u00E7\u00E3o e consumo")
new_category(tematicas, "Rela\u00E7\u00F5es internacionais")
new_category(tematicas, "Marco Legal")
new_category(tematicas, "Finan\u00E7as Solid\u00E1rias")
new_category(tematicas, "Comunica\u00E7\u00E3o")
new_category(tematicas, "Pol\u00EDticas p\u00FAblicas")
new_category(tematicas, "Organiza\u00E7\u00E3o do movimento")
new_category(tematicas, "Software, cultura e conhecimentos livres")
new_category(tematicas, "Agroecologia")
new_category(tematicas, "Pesquisa e tecnologia")
new_category(tematicas, "Com\u00E9rcio justo e solid\u00E1rio")
new_category(tematicas, "Cultura")

cadeias = new_category(nil, "Redes/Cadeias", 3)
new_category(cadeias, "Agropecu\u00E1ria, extrativismo e pesca")
new_category(cadeias, "Alimenta\u00E7\u00E3o")
new_category(cadeias, "Artesanato")
new_category(cadeias, "Ind\u00FAstria")
new_category(cadeias, "Confec\u00E7\u00E3o, fia\u00E7\u00E3o e tecelagem")
new_category(cadeias, "Reciclagem")
new_category(cadeias, "Turismo")
new_category(cadeias, "Constru\u00E7\u00E3o")
new_category(cadeias, "Cr\u00E9dito e finan\u00E7as")
new_category(cadeias, "Sa\u00FAde")
new_category(cadeias, "Educa\u00E7\u00E3o e forma\u00E7\u00E3o")
new_category(cadeias, "Limpeza e higiene")
new_category(cadeias, "Cultura")
new_category(cadeias, "Cadeia do mel")
new_category(cadeias, "Cadeia do algod\u00E3o agroecol\u00F3gico")
new_category(cadeias, "Cadeia das sementes")
new_category(cadeias, "Cadeia da fruta")
done

print "Creating regions: "
territorios = new_region(nil, "Territ\u00F3rios", 2)
nacional = new_region(territorios, "Nacional")
internacional = new_region(territorios, "Internacional")
centro_oeste = new_region(nacional, "Regi\u00E3o Centro-Oeste")
mt = new_state(centro_oeste, "Mato Grosso")
ms = new_state(centro_oeste, "Mato Grosso do Sul")
go = new_state(centro_oeste, "Goi\u00E1s")
df = new_state(centro_oeste, "Distrito Federal")
nordeste = new_region(nacional, "Regi\u00E3o Nordeste")
al = new_state(nordeste, "Alagoas")
ba = new_state(nordeste, "Bahia")
ce = new_state(nordeste, "Cear\u00E1")
ma = new_state(nordeste, "Maranh\u00E3o")
pb = new_state(nordeste, "Para\u00EDba")
pe = new_state(nordeste, "Pernambuco")
pi = new_state(nordeste, "Piau\u00ED")
rn = new_state(nordeste, "Rio Grande do Norte")
se = new_state(nordeste, "Sergipe")
norte = new_region(nacional, "Regi\u00E3o Norte")
ac = new_state(norte, "Acre")
ap = new_state(norte, "Amap\u00E1")
am = new_state(norte, "Amazonas")
pa = new_state(norte, "Par\u00E1")
ro = new_state(norte, "Rond\u00F4nia")
rr = new_state(norte, "Roraima")
to = new_state(norte, "Tocantins")
sudeste = new_region(nacional, "Regi\u00E3o Sudeste")
mg = new_state(sudeste, "Minas Gerais")
sp = new_state(sudeste, "S\u00E3o Paulo")
rj = new_state(sudeste, "Rio de Janeiro")
es = new_state(sudeste, "Esp\u00EDrito Santo")
sul = new_region(nacional, "Regi\u00E3o Sul")
pr = new_state(sul, "Paran\u00E1")
rs = new_state(sul, "Rio Grande do Sul")
sc = new_state(sul, "Santa Catarina")
done
