#!/bin/sh

set -e

cd /vagrant
./script/set-apt-proxy

sudo DEBIAN_FRONTEND=noninteractive apt-get install -qy postfix
sudo postconf virtual_alias_maps=hash:/etc/postfix/virtual
sudo tee /etc/postfix/virtual <<EOF
@localhost.localdomain  vagrant
EOF
sudo postmap /etc/postfix/virtual
sudo service postfix reload

./script/quick-start
